# Generated by Django 5.1 on 2024-08-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('senha', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=16)),
                ('dt_nascimento', models.DateField()),
                ('pdf_avaliacao', models.FileField(upload_to='')),
                ('pdf_ficha', models.FileField(upload_to='')),
                ('superuser', models.BooleanField(default=False)),
            ],
        ),
    ]
