# Generated by Django 5.1 on 2024-08-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechFit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pdf_avaliacao',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pdf_ficha',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
